public class Employees {
    public static void employeeName() {

        List<string> listEmployeeName = new List<string>();

        listEmployeeName.add('Jack');
        listEmployeeName.add('Emily');
        listEmployeeName.add('David');
        listEmployeeName.add('Kevin');
        listEmployeeName.add('Susan');
        listEmployeeName.add('Matheus');

        listEmployeeName.sort();

        System.debug('The names are:' + listEmployeeName);
        

  }
}
