// RankHandler rh = new RankHandler();
// System.debug(rh.rankPrize(1));
// System.debug(rh.rankPrize(2));
// System.debug(rh.rankPrize(3));
// System.debug(rh.rankPrize(8));
// System.debug(rh.rankPrize(12));


RankHandler rif = new RankHandler();
System.debug(rif.rankPrizeIf(1));
System.debug(rif.rankPrizeIf(2));
System.debug(rif.rankPrizeIf(3));
System.debug(rif.rankPrizeIf(8));
System.debug(rif.rankPrizeIf(15));


